name: Go
on:
  push:
    branches:
      - gh_actions
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: ['1.11.x', '1.12.x', '1.13.x', '1.14.x', '1.15.x', 'tip']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        if: matrix.go != 'tip'
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/setup-go@v2
        if: matrix.go == 'tip'
        with:
          stable: true
      - name: install tip
        if: matrix.go == 'tip'
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          echo "$HOME/gotip/bin" >> "$GITHUB_PATH"
      - name: go test
        run: |
          go version
          go env
          go test -v -race ./...
